apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway.yaml
  - product-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - inventory-service.yaml
  - email-service.yaml
  - admin-ui.yaml

images:
  - name: iamnmk777/ecom-api-gateway
    newTag: prod
  - name: iamnmk777/ecom-product-service
    newTag: prod
  - name: iamnmk777/ecom-order-service
    newTag: prod
  - name: iamnmk777/ecom-payment-service
    newTag: prod
  - name: iamnmk777/ecom-inventory-service
    newTag: prod
  - name: iamnmk777/ecom-email-service
    newTag: prod
  - name: iamnmk777/ecom-admin-ui
    newTag: prod
